name: Generate Documents
on:
  push:
    branches:
      - main
    paths:
      - '**/*.c'
      - '**/*.h'
      - '.github/workflows/*'
      - 'Makefile'
      - '**/*.nix'
      - 'Doxyfile'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
      - run: nix-env -f ./nix/pkgs.nix -iA doxygen
      - name: build documents
        run: doxygen
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
          destination_dir: .
          keep_files: true
